FILE_OUTLAY_BY_AGENCY = "outlays_by_agency.csv"
FILE_OUTLAY_BY_AGENCY_PERCENTAGES = "outlays_by_agency_percentages.csv"
FILE_NPS_ANNUAL_USE = "nps_annual_use_data_all_time.csv"
FILE_NPS_USE_BY_MONTH = "NPS_use_data_1970-2016_monthly.csv"
FILE_TEST = "testfile.csv"
